When on board HMS Beagle, as naturalist, I was much struck with certain facts in the distribution of the inhabitants of South America, and in the geological relations of the present to the past inhabitants of that continent. These facts seemed to me to throw some light on the origin of species - that mystery of mysteries, as it has been called by one of our greatest philosophers.

That many and grave objections may be advanced against the theory of descent with modification through natural selection, I do not deny. I have endeavoured to give to them their full force. Nothing at first can appear more difficult to believe than that the more complex organs and instincts should have been perfected, not by means superior to, though analogous with, human reason, but by the accumulation of innumerable slight variations, each good for the individual possessor. Nevertheless, this difficulty, though appearing to our imagination insuperably great, cannot be considered real if we admit the following propositions, namely, that gradations in the perfection of any organ or instinct, which we may consider, either do now exist or could have existed, each good of its kind, that all organs and instincts are, in ever so slight a degree, variable; and, lastly, that there is a struggle for existence leading to the preservation of each profitable deviation of structure or instinct. The truth of these propositions cannot, I think, be disputed.

It is, no doubt, extremely difficult even to conjecture by what gradations many structures have been perfected, more especially amongst broken and failing groups of organic beings, which have suffered much extinction; but we see so many strange gradations in nature, that we ought to be extremely cautious in saying that any organ or instinct, or any whole being, could not have arrived at its present state by many graduated steps. There are, it must be admitted, cases of special difficulty on the theory of natural selection; and one of the most curious of these is the existence of two or three defined castes of workers or sterile females in the same community of ants; but I have attempted to show how these difficulties can be mastered.
With respect to the almost universal sterility of species when first crossed, which forms so remarkable a contrast with the almost universal fertility of varieties when crossed, I must refer the reader to the recapitulation of the facts given at the end of the eighth chapter, which seem to me conclusively to show that this sterility is no more a special endowment than is the incapacity of two trees to be grafted together; but that it is incidental on constitutional differences in the reproductive systems of the intercrossed species. We see the truth of this conclusion in the vast difference in the result, when the same two species are crossed reciprocally; that is, when one species is first used as the father and then as the mother.

Although the fertility of varieties when intercrossed and of their mongrel offspring has been asserted by so many authors to be universal, this cannot be considered correct after the facts given on the authority of Gärtner and Kölreuter. Nor is the very general fertility of varieties, when crossed, surprising, when we remember that it is not likely that either their constitutions or their reproductive systems should have been profoundly modified. Moreover, most of the varieties which have been experimented on have been produced under domestication; and as domestication (I do not mean mere confinement) apparently tends to eliminate sterility, we ought not to expect it also to produce sterility.

The sterility of hybrids is a very different case from that of a first cross, for their reproductive organs are more or less functionally impotent; whereas in first crosses, the organs of both species are in a perfect condition. As we continually see that organisms of all kinds are rendered in some degree sterile from their constitutions having been disturbed by slightly different and new conditions of life, we need not feel surprise at hybrids being in some degree sterile, for their constitutions can hardly fail to have been disturbed from being compounded of two distinct organisations. This parallelism is supported by another parallel, but directly opposite, class of facts, namely, that the vigour and fertility of all organic beings are increased by slight changes in their conditions of life, and that the offspring of slightly modified forms or varieties acquire from being crossed increased vigour and fertility. So that, on the one hand, considerable changes in the conditions of life and crosses between greatly modified forms, lessen fertility; and on the other hand, lesser changes in the conditions of life and crosses between less modified forms, increase fertility.

Turning to geographical distribution, the difficulties encountered on the theory of descent with modification are serious enough. All the individuals of the same species, and all the species of the same genus, or even higher group, must have descended from common parents; and therefore, in however distant and isolated parts of the world they are now found, they must in the course of successive generations have passed from some one part to the others. We are often wholly unable even to conjecture how this could have been effected. Yet, as we have reason to believe that some species have retained the same specific form for very long periods, enormously long as measured by years, too much stress ought not to be laid on the occasional wide diffusion of the same species; for during very long periods of time there will always have been a good chance for wide migration by many means. A broken or interrupted range may often be accounted for by the extinction of the species in the intermediate regions. It cannot be denied that we are as yet very ignorant of the full extent of the various climatal and geographical changes which have affected the earth during modern periods; and such changes will obviously have greatly facilitated migration. As an example, I have attempted to show how potent has been the influence of the Glacial period on the distribution both of the same and of representative species throughout the world. We are as yet profoundly ignorant of the many occasional means of transport. With respect to distinct species of the same genus inhabiting very distant and isolated regions, as the process of modification has necessarily been slow, all the means of migration will have been possible during a very long period; and consequently the difficulty of the wide diffusion of species of the same genus is in some degree lessened.

